version: '3.7'
services:

  server:
    build: .
    container_name: server
    ports:
      - 80:80
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./database-volume:/data/db
